name: Test FastAPI Video Generator

on:
  push:
    branches: [ main ]

jobs:
  test-api:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Install Python dependencies
      run: |
        pip install fastapi uvicorn jinja2 python-multipart
        pip install torch transformers huggingface-hub
        # Add any other dependencies from your requirements.txt

    - name: Create directory structure
      run: |
        mkdir -p app/static app/templates app/videos

    - name: Test FastAPI application
      run: |
        python -c "
from fastapi import FastAPI
import uvicorn
import os

# Test basic FastAPI setup
app = FastAPI()

@app.get('/')
async def root():
    return {'message': 'FastAPI is working'}

print('✓ FastAPI application can be imported and initialized')
        "

    - name: Check application structure
      run: |
        echo "Checking application files..."
        if [ -f "app.py" ]; then
          echo "✓ app.py exists"
          python -c "
try:
    from app import app
    print('✓ Application can be imported successfully')
except Exception as e:
    print('✗ Error importing app:', e)
          "
        else
          echo "✗ app.py not found"
          exit 1
        fi
