name: Run LTX Video App

on:
  push:
    branches: [ main ]

jobs:
  run-app:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Clone and run LTX Video
      run: |
        git clone https://huggingface.co/spaces/Jaan22/ltx-video-distilled
        cd ltx-video-distilled
        pip install -r requirements.txt
        python app.py
